### ISSUE TITLE
Visualisation des champs obligatoires en saisie

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#11]
Suite au ticket https://github.com/docalist/docalist/issues/350 et à défaut de contrôle de saisie,

Une correctrice me demande si nous ne pouvons pas améliorer la signalétique pour rappeler les champs obligatoires (ce qui représente 3 champs sur 4 mais bon...).

Je propose que nous mettions en rouge les libellés des champs obligatoires

comme ci-dessous : 

![capture](https://cloud.githubusercontent.com/assets/5398758/9732692/24700cf6-5626-11e5-80f6-b409fc94a45b.JPG)

Je suis passé par le réglage du formulaire de saisie du .NET

![capture1](https://cloud.githubusercontent.com/assets/5398758/9732812/fb6b2fe2-5626-11e5-9e5d-82b5ab504bfe.JPG)

@ocormont : est-ce que tu es d'accord ?
@daniel-menard : est-ce que c'est le code approprié ?

**Comment by ocormont** [comment]
ok pour moi

**Comment by Nicolas-L** [comment]
OK je vais le faire pour la grille article de la base Biblio.
En attendant la fonctionnalité "champ obligatoire" sur le paramétrage des champs

**Comment by Nicolas-L** [comment]
Pas terrible ma bidouille finalement : dans les champs répétables, le code s'affiche dans la grille de saisie après le **`+`**

![capture](https://cloud.githubusercontent.com/assets/5398758/10116611/7449903c-6439-11e5-91a7-45165a61c84b.JPG)
