### ISSUE TITLE
Créer la Capacité edit_champ_admin

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#15]
Suite à la remarque d'Olivier dans le ticket https://github.com/docalist/docalist/issues/353, nous avons décelé une confusion entre Rôle et Capabilities pour le champ OP.

Il faut créer la capicité _edit_champ_admin_

**Comment by daniel-menard** [comment]
Deux remarques : 
- je l'aurais mise au pluriel, dans la mesure où cela conditionne l'affichage de plusieurs champs de gestion dans le formulaire de saisie : `edit_champs_admin`.
- je pense que vous aurez aussi besoin d'un droit pour déterminer qui peut _voir_ les champs de gestion, et comme ce ne sont pas forcément les mêmes personnes qui peuvent saisir et voir, je propose de créer également la capacité `voir_champs_admin`.

Vous pourrez ainsi dissocier les fonctions lire et écrire et attribuer ces capacités comme vous le souhaitez aux groupes et utilisateurs qui en ont besoin.

En terme de paramétrage, dans la grille de base, on aurait donc la capacité `voir_champs_admin` qui serait requise pour tous les champs de gestion et dans le formulaire de saisie, c'est la capacité `edit_champs_admin` qui serait requise.

**Comment by ocormont** [comment]
La capacité `edit_champs_admin` a été créé, et a été donné aux rôles correcteur.base.prisme et producteur.base.prisme
![capture](https://cloud.githubusercontent.com/assets/5398792/9853269/17166e6a-5b03-11e5-9b92-843a543ac246.JPG)

La capacité `voir_champs_admin` a été créé, et a été donné aux rôles membre.prisme
![capture2](https://cloud.githubusercontent.com/assets/5398792/9853326/4b927d5a-5b03-11e5-8ca9-70742dcc1632.JPG)

### Dans le type de notice Article
- Les champs suivants de la grille de base ont reçu la capacité `voir_champs_admin`
  Statut
  Création
  Créé par
  Dernière modification
  Producteur de la notice
  membreprisme
  Erreurs()  (ce champ a une écriture incorrecte : le remplacer par : erreur(s) ?)
- Le champ suivant de la grille Formulaire de saisie ont reçu la capacité `edit_champs_admin`
  Producteur de la notice

### Conclusion :

L'administrateur ne pouvait plus saisir le champ Producteur de la notice. Après modification, cela fonctionne désormais
Après modification, les producteurs peuvent toujours saisir leur organisme.
Cependant, ce champ Producteur de la notice est contenu dans le bloc Informations de Gestion qui est refermé, il faudrait le rendre plus visible. J'ouvre un nouveau ticket #21

**Comment by Nicolas-L** [comment]
@ocormont : Est-ce que tu pourrais faire le changement aussi sur le .NET ?

**Comment by ocormont** [comment]
C'est fait
