### ISSUE TITLE
Créer la base Regard(s) social

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#16]
Créer la BDD Regard(s) social avec les notices _Film_ pour commencer. Il y aura d'autres types de notices par la suite.

Il s'avère plus judicieux pour la com audiovisuel de créer sa propre BDD. En effet, les requêtes multibases étant possibles, il vaut mieux créer un Rôle du genre _producteur.base-audiovisuelle_ (titre à définir).

Ceci permettra d'éviter les interférences entre l'activité de la com audio et celle des producteurs.

Voir aussi #7

**Comment by ocormont** [comment]
- La base Regard(s) social a été créée
- Les membres de cette commission ont le rôle de producteur.base-audiovisuelle qui permet d'ajouter une notice et la modifier/publier
- Création d'une page wordpress base-audiovisuelle qui permet d'avoir la liste des notices de cette base (liste des réponses en affichage court)
