### ISSUE TITLE
Créer la base Site web

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#17]
1. Créer la BDD Site web (titre exacte à définir avec la com Annuaire).
2. Migrer la base du .NET vers le .ORG ou récupérer le fichier au format Prisme 2012 pour l'importer

Types de notices : Site web uniquement

Voir aussi #7

**Comment by ocormont** [comment]
- La base Site web a été créée
- Création du rôle de producteur.base-siteweb qui permet d'ajouter une notice et la modifier/publier
- Création d'une page wordpress base-siteweb qui permet d'avoir la liste des notices de cette base (liste des réponses en affichage court)

### Reste à faire
- Demander la liste des membres de la commission. (je m'en occupe)
- Demander la dernière base à jour et l'importer (voir si la dernière Bdd importée a été modifié) (je m'en occupe)

**Comment by ocormont** [comment]
Les membres et rôles ont été créés.

Un import a été fait, 338 notices importés avec le statut attente.
Par rapport à la bdd d'origine, seuls les champs Mail et LI n'ont pas été importé
Reste à la commission Site web de contrôler le résultat

**Comment by Nicolas-L** [comment]
Je pense que ce n'est pas la bonne base car j'avais vraiment toiletté tous les titres, les sigles étaient bien en majuscules, etc.

Ici on a : Unccas, Cpds, etc.

**Comment by ocormont** [comment]
C'est rectifié

**Comment by Nicolas-L** [comment]
Petite remarque : la date de création de la notice a été enregistrée également comme étant la date de publication de la référence (Champ : Information bibliographique) ce qui du coup devient une erreur d'indexation.
Il faudrait enlever purement et simplement cette info, ou signifier l'erreur aux producteurs de l'annuaire pour qu'ils corrigent ce champs lors de la validation.
