### ISSUE TITLE
Rendre le Champ Producteur de la notice plus visible

### ISSUE THREAD

**Issue by ocormont** [reseau-prisme/site#21]
Le champ Producteur de la notice est contenu dans le bloc Informations de Gestion qui est, d'après mes souvenirs, refermé.
Ce champ devait être à l'origine autocomplété mais le développement de cette fonctionnalité a été reporté.
Dans les dernières notices, j'ai remarqué que l'info n'était pas notée.
Je pense que cela est dû à un manque de visibilité.

Je propose soit :
- Mettre ce champ dans un nouveau bloc tout en haut de la grille de saisie
- Mettre ce champ dans un nouveau bloc tout en bas de la grille de saisie, mais avant le bloc Infos de gestion
- Mettre ce champ dans un bloc existant, mais lequel

Qu'en pensez vous ?

**Comment by Nicolas-L** [comment]
Pourquoi on ne laisserait-on pas ouvert ce groupe de champs ? On mettrait la typo en rouge pour signifier qu'il faut le remplir obligatoirement.

**Question**, j'ai oublié de la poser dans le ticket https://github.com/docalist/docalist/issues/353 mais OP est un champ texte libre ? je pensais que c'était un champ sur table... cf ici : https://github.com/reseau-prisme/format-prisme-2014/wiki/table-producteurs

**Comment by ocormont** [comment]
Depuis la prise en main de Docalist par les membres de Prisme, ce champ est renseigné comme il faut
