### ISSUE TITLE
Filtre sur Type dans la recherche Avancée

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#22]
il faudrait rajouter les autres types de notice dans la recherche avancée, _a minima_ le type **Site web**

![capture](https://cloud.githubusercontent.com/assets/5398758/9879342/433c653e-5bc7-11e5-960d-95b02d3a70d2.JPG)

**Comment by ocormont** [comment]
En cours avec la migration du site de Prisme dans une version plus récente
