### ISSUE TITLE
Message WP de MAJ

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#23]
Connecté en tant qu'Admin ou en tant que **Producteur**, on a ce message quand on veut accéder au back office

![capture](https://cloud.githubusercontent.com/assets/5398758/9898443/8b14ff8e-5c52-11e5-93cc-e0cec0e88eeb.JPG)

Ça doit faire suite à la mise à jour automatique vers WP 4.3.1
- J'imagine qu'on doit cliquer sur le bouton de Mise à jour...

**Comment by daniel-menard** [comment]
Je pense que quelqu'un a fini par cliquer sur le bouton "mettre à jour" car le message n'apparaît plus...

Effectivement, c'est lié à la mise à jour de WordPress. Sur le fond, ce n'est pas normal, car seules les mises à jours mineures sont installées automatiquement (passage de la 4.3.0 à la 4.3.1 dans le cas présent) et une mise à jour mineure ne devrait pas, à mon sens, nécessiter une mise à jour de la structure de la base de données.

Le second problème c'est que le message s'affiche pour les admins et les producteurs. En fait, WordPress refuse l'accès au back-office si une mise à jour de la base est requise, donc toute personne qui essaie d’accéder au BO aura le message.

Dans les deux cas, c'est la façon de fonctionner de WordPress et on ne peut pas y faire grand chose, sauf à désactiver complètement les mises à jour WordPress, ce qui n'est pas souhaitable.

**Comment by Nicolas-L** [comment]
OK merci pour la réponse ! je tenais à signaler le cas de figure. Je ferme.
