### ISSUE TITLE
Champ "Créé par" sur les notices importées

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#25]
Dans le champ "créé par" on a le nom du compte qui a effectivement importé la notice.
Même s'il ne faut pas confondre avec "producteur", je pense qu'il aurait été plus "adéquat" d'avoir un nom neutre (du genre "Prisme") pour les notices qui sont créées par import.

![capture](https://cloud.githubusercontent.com/assets/5398758/9935050/d6ccd9bc-5d54-11e5-883f-e33353e1a7cd.JPG)

**Comment by ocormont** [comment]
Depuis la dernière version de Docialist, possibilité de modifier à posteriori le créateur de la notice
