### ISSUE TITLE
Film de la base Prisme

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#29]
Il faudrait migrer les notices Film de la _Base Prisme_ vers la base _Audiovisuelle_

**Comment by Nicolas-L** [comment]
Dans le .NET, j'ai importé le fichier Film issu des références de la bdd Prisme (77 notices converties en Prisme 2012).
- toutes les données sur table ou presque apparaissent précédées de la mention "invalide" alors que les termes sont bien dans les listes...

![capture](https://cloud.githubusercontent.com/assets/5398758/10309025/5b8ccbe6-6c3a-11e5-9299-9981fcde567a.JPG)

**Comment by ocormont** [comment]
Depuis la possibilité de migrer les notices d'une base à l'autre, ticket clos
