### ISSUE TITLE
Affichage icone de la bdd Siteweb

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#32]
**Micro question :** pourquoi l'icone n'est pas prise en compte dans le menu de la base Site web ???

![capture](https://cloud.githubusercontent.com/assets/5398758/10370008/65854818-6ddd-11e5-8dc6-9660c74157dc.JPG)

**Comment by daniel-menard** [comment]
Il y avait un espace en trop (au début) dans le nom de l'icône : 
![image](https://cloud.githubusercontent.com/assets/3940667/10659928/c586077c-78a3-11e5-86aa-b6ff5b2ae920.png)

J'ai corrigé : 
![image](https://cloud.githubusercontent.com/assets/3940667/10659993/266e42de-78a4-11e5-8493-a03e40673abb.png)
