### ISSUE TITLE
Recherche Base Prisme Vs tout le site

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#34]
La recherche sur tout le site renvoie : 

![capture](https://cloud.githubusercontent.com/assets/5398758/10390041/31adfad2-6e76-11e5-8188-d7281132d016.JPG)

Cela porte à confusion (Article du site / Article de périodiques... ; "Page" de quoi ?)

Selon moi, il serait plus judicieux de  pouvoir faire une requête soit sur un ensemble de bases défini (option par défaut), soit sur les articles et pages du site (soit l'un soit l'autre mais pas les deux en même temps).

![capture](https://cloud.githubusercontent.com/assets/5398758/10390918/e023b3d6-6e7b-11e5-8403-aba44e564c14.JPG)

**Comment by Nicolas-L** [comment]
Par ailleurs, si on sélectionne une base dans l'exemple de la première capture ci-dessus, on tombe sur  la liste des notices de cette base mais le formulaire de saisie présent en tête de page sélectionne par défaut "base Prisme uniquement".

![capture](https://cloud.githubusercontent.com/assets/5398758/10508256/3631cf20-7326-11e5-9cf7-f80fdcef8c98.JPG)
- Il faudrait - pour le moment - qu'il soit sur "tout le site" par défaut

**Comment by Nicolas-L** [comment]
@daniel-menard : ce tout dernier point commence à être urgent avec l'ouverture progressive de plusieurs bases.
Les différents producteurs vont faire des requêtes sur leurs bases et ils risquent d'être enquiquinés par ce détail (_base prisme uniquement_).

**Comment by ocormont** [comment]
En cours avec migration de la nouvelle version de Docalist
