### ISSUE TITLE
Export hors base biblio

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#40]
Il n'est pas possible de générer des fichiers d'export depuis des notices issues d'une autre base que la base Prisme. (Sur le .ORG).

Voici le message qui s'affiche, quelque soit le nombre de notices comprises dans la sélection. (Ici : notices _Legislation_ de la bdd _Texte officiel_).

![capture](https://cloud.githubusercontent.com/assets/5398758/10881951/41e00306-8167-11e5-8095-f8a9336f324e.JPG)

**Comment by ocormont** [comment]
Format d'export prévu à l'origine ne portait que sur le type Article.
A développer si nécessaire
