### ISSUE TITLE
Recherche par date de création de notice

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#42]
Même ayant bien relu le docalist/docalist#286 je ne parviens pas à trouver la bonne requête pour avoir une liste de toutes les notices créées en 2015 (demande pour faire un rapport annuel).
- Si on fait [`creation:>[2015 TO 2016]`](http://www.documentation-sociale.org/base-prisme/recherche/?q=creation%3A%3E%5B2015+TO+2016%5D) et même [`creation:<[2015 TO 2016]`](http://www.documentation-sociale.org/base-prisme/recherche/?q=creation%3A%3C%5B2015+TO+2016%5D), ça donne pareil : 1512 notices dont certaines sont saisies en 2005 (par exemple : Réf : 58785 ; DS : 2005-11-24)
- Si on fait `creation:[2015 TO 2016]` ça donne rien
- Si on fait avec `date:[2015 TO 2016]` ça requête pas sur le champ de la date de création des notices

**Comment by daniel-menard** [comment]
Bonjour Nicolas,

J'ai fait un peu de débogage et en fait c'est un bug : les champs creation et lastupdate ne sont pas correctement indexés.

Apparemment, le problème n'est pas nouveau : ça daterait d'une modification effectuée dans le code le 1er avril 2015 (il y a des dates comme ça, qu'il faudrait éviter...)

Le problème c'est que l'indexation de ces deux champs a été changée dans le code (si on crée une nouvelle base, cela fonctionne), mais la modification n'a pas été répercutée sur les bases et les types qui existaient déjà (pour ne pas perdre les personnalisations faites dans les grilles).

Il faut donc que j'aille "modifier à la main" les paramètres des bases pour indiquer le bon type de données à utiliser pour les deux champs. Ensuite il faudra juste faite une réindexation complète et tout rentrera dans l'ordre.

Malheureusement, cela va me prendre du temps car la modification doit être faite à la fois sur le .net et sur le .org, il faut le faire pour chaque base, il faut le faire pour chaque type et ensuite pour chacune des grilles qui composent chaque type.

Pour que vous ne soyez pas bloqué (j'imagine que c'est pour faire des stats pour le rapport d'activité ?), est-ce qu'en attendant vous pouvez vous en sortir en interrogeant par numéro de référence ?

**Comment by Nicolas-L** [comment]
Oui, c'est ce que j'ai fait,
- Pour les notices saisies en ligne c'est facile vu qu'on a l'[historique de toutes les semaines](http://www.documentation-sociale.org/prisme/produits-services/base-prisme/listes-semaines/),
- Pour l'antériorité, je suis aller rechercher dans la liste du back office en supposant que les DS se suivent dans l'ordre chrono.

Je pense que le chiffre est [OK](http://www.documentation-sociale.org/base-prisme/recherche/?q=ref%3A%5B78007+TO+79609%5D)

**Comment by daniel-menard** [comment]
Finalement, j'ai réussi à trouver une solution pour faire les modifications sans y passer la journée.

Les champs creation et lastupdate sont à nouveau correctement indexés (j'ai lancé une réindexation complète).

En interrogeant par [date de création sur tout 2015](http://www.documentation-sociale.org/base-prisme/recherche/?q=creation%3A%5B2015-01-01+TO+2016-01-01%5D), j'obtiens un chiffre légèrement différent du vôtre (1585 au lieu de 1577). 

La différence s'explique probablement par les raisons suivantes :
- La recherche sur `ref:[78007 TO 79609]` ressort quelques notices (15) qui ne sont pas des notices de 2015. On peut les avoir via la requête suivante : [`ref:[78007 TO 79609] AND NOT creation:[2015-01-01 TO 2016-01-01]`](http://www.documentation-sociale.org/base-prisme/recherche/?q=ref%3A%5B78007+TO+79609%5D+AND+NOT+creation%3A%5B2015-01-01+TO+2016-01-01%5D&explain-query=1)
  
  En enlevant ces 15 notices du chiffre que vous avez trouvé, on obtient 1562 notices (1577-15).
- Par ailleurs, lors de l'import final qui a été fait le 19/06/2015, il y avait [23 notices qui n'avaient pas de dates](http://www.documentation-sociale.org/base-prisme/recherche/?q=creation%3A%5B2015-06-19+TO+2015-06-20%5D) et le champ creation a probablement été initialisé avec la date du jour ([exemple sur cette notice](http://www.documentation-sociale.org/base-prisme/51953/)).
  
  En enlevant ces 23 notices du chiffre que j'ai trouvé, on obtient également 1562 notices (1585-23). 

Equation finale : [`ref:[78007 TO 79609] AND creation:[2015-01-01 TO 2016-01-01]`](http://www.documentation-sociale.org/base-prisme/recherche/?q=ref%3A%5B78007+TO+79609%5D+AND+creation%3A%5B2015-01-01+TO+2016-01-01%5D), 1562 notices.
