### ISSUE TITLE
Table thésaurus modifiable

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#43]
_From @Nicolas-L on March 29, 2016 10:11_

Passer la table thésaurus `Prisme - Thesaurus, version 2.2 du 16/06/15 en caractères riches. - thesaurus-prisme-2.2` en modifiable pour les admin pour pouvoir effectuer des mises à jour ou des corrections.

_Copied from original issue: docalist/docalist#370_

**Comment by daniel-menard** [comment]
J'ai réfléchi à ça depuis notre dernière conversation téléphonique. 

En fait ce n'est pas une bonne idée : si on veut que [le numéro de version ait un sens](http://semver.org/lang/fr/), il ne faut pas changer après coup le contenu de la table sinon, le nom "version 2.2 du 16/05/15" ne voudra plus rien dire.

En fait, ce qu'on veut, c'est commencer le travail sur la version 2.3 du thesaurus. Du coup, la bonne méthode consiste à copier la table (ça crée une table personnalisée donc elle sera modifiable) et à la nommer "version 2.3".

Vous pouvez ensuite faire toute les modifs que vous voulez, et tester cette nouvelle version (sur le .net) en modifiant la table topics.

Une fois que cette nouvelle version est prête, on peut committer les données (pour que la nouvelle version soit enregistrée dans le dépôt du projet), la rendre non modifiable (i.e. on acte "fin du travail sur la 2.3") et l'activer sur le .org.

En faisant comme ça, on a des versions clairement identifiées et on peut assez facilement voir les modifications apportées en faisant un "diff" (une comparaison) entre deux versions (il existe des outils en ligne tels que https://www.diffchecker.com/ ou http://www.quickdiff.com/ qui peuvent aider).

Qu'en pensez-vous ?

**Comment by Nicolas-L** [comment]
Oui, c'est effectivement une procédure plus prudente : 
1. Copier et renommer la table sur le .net
2. Modifier, tester, valider la table sur le .net
3. Activer la table sur le .org

Par contre, il faudrait que ce soit les admin qui puissent activer cette table, du coup, est-ce qu'on ne devrait pas plutôt la passer en "table personnalisée" sur le .org. On prévoit deux mises à jour par an et il faut qu'on soit le plus indépendants possible sur cette manip.

**Remarque annexe** : on ne peut copier coller plus de 1000 lignes des tables (table Docalist => Excel ou si on sort de la fonction Copier interne de Docalist) or sur un thésaurus en contenant plus de 3000 ça nous fait des manip assez laborieuses.

**Comment by daniel-menard** [comment]
> Par contre, il faudrait que ce soit les admin qui puissent activer cette table

La table `prisme-topics` est une table personnalisée, donc vous pouvez la modifier vous -même pour activer la nouvelle version.

> on ne peut copier coller plus de 1000 lignes des tables

Je ne connaissais pas cette limite, mais effectivement, que ce soit avec excel ou libre-office, on est limité à 1000. Est-ce indispensable de passer par excel pour modifier la table ?

**Comment by Nicolas-L** [comment]
> La table `prisme-topics` est une table personnalisée, donc vous pouvez la modifier vous -même pour activer la nouvelle version.

oui il faut juste passer la table thésaurus-prisme 2.3 en table perso (la 2.2 est actuellement en prédéfinie).

> Je ne connaissais pas cette limite, mais effectivement, que ce soit avec excel ou libre-office, on est limité à 1000. Est-ce indispensable de passer par excel pour modifier la table ?

Non. En fait je pensais copier depuis le .org et coller sur le .net (et pas XL) mais en fait, la 2.2 est déjà chargée sur le .net. Il suffit donc de la copier en table perso. Par contre c'est pour transmettre la table complète aux collègues qu'on a ce besoin.

**Comment by Nicolas-L** [comment]
> > Non. En fait je pensais copier depuis le .org et coller sur le .net (et pas XL) mais en fait, la 2.2 est déjà chargée sur le .net. Il suffit donc de la copier en table perso. Par contre c'est pour transmettre la table complète aux collègues qu'on a ce besoin.

En fait on aura quand même besoin de copier la table V.n+1 du .net (finalisée) pour la coller sur le .org (pour l'activer). On aura donc bien à prévoir une petite séance de copier coller dans le sens .net=>.org
