### ISSUE TITLE
Migration des notices de type autres que Articles de la base Prisme vers les bases correspondantes

### ISSUE THREAD

**Issue by ocormont** [reseau-prisme/site#48]
La base Prisme contient en majorité des notices de type Articles mais aussi d'autres types.
Au début du développement de Docalist, ce choix de créer une base unique pour tous types de notices était opportun, ce n'est plus le cas aujourd'hui.

Il faudrait donc migrer l'ensemble des notices de type non articles vers les bases correspondantes.
A ce jour, dans la base Prisme, nous avons
- Article de périodique : 68099
- Livre : 12349
- Mémoire ou thèse : 493
- Film : 77

Il est impossible actuellement d'exporter ces notices et de les réimporter dans la base idoine de manière simple. En effet, le format temporaire d'import 2012 n'est pas disponible dans les formats d'export.

Afin de déterminer une procédure de migration, nous envisageons de tester sur les notices de type livres sur le site de développement
- Export de la Base Prisme des notices de type Livre au format 2011
- Modification via Excel du fichier pour le rendre compatible avec le format 2012
- Import du fichier dans la Base Livre
- Comparaison des notices entre les deux bases pour vérifier l'exactitude des informations dans les différents champs
- Suppression des notices Livres de la Base Prisme

Une fois la procédure approuvée, faire la manipulation sur le site de production pour tous les types de notices. Il faudra en outre créer une Base Mémoire pour importer les notices Mémoires.

**Comment by ocormont** [comment]
En voulant faire le test sur le site de développement, je me suis rendu compte qu'il est impossible en l'état d'exporter un fichier de 12349 notices livres, seul les 100 premières notices sont dans le fichier d'export.
Comment faire ?

**Comment by daniel-menard** [comment]
Bonjour Olivier,

Je viens de tester et effectivement, il y a plusieurs limites fixées en dur dans le code qui font qu'on ne peut pas tout exporter (c'est pas top, cette affaire : on a une page de réglages dans laquelle on peut paramétrer les limites mais elles ne sont pas prises en compte dans le code...)

Comme je ne peux pas facilement modifier le code du plugin (tant que je n'ai pas migré tout prisme vers la nouvelle version de docalist), j'ai modifié directement les fichiers sur le serveur (sur le site .net) et j'ai mis j'ai mis une limite à 99999 notices.

Ce n'est pas très propre, mais ça nous permettra d'avancer sur ce ticket. 

J'ai fait un test et j'ai réussi à exporter les 12349 notices livres de la base prisme (l'export prend longtemps, il faut être patient) et j'obtiens le bon nombre de notices (j'ai compté le nombre de "+++" dans le fichier résultat).

Pouvez-vous tester ?

Si c'est OK, il faudra que je fasse la même modif que ce que je viens de faire sur les codes sources du site de prod (pas long). Dites-moi quand ce sera le bon moment.

----

Mémo pour moi : 

- fichier `/docalist-biblio-export/class/Plugin.php`
- ligne 218 : limite codée en dur à 100, remplacer par 99999
- ligne 265 : limite codée en dur à 1000, remplacer par 99999

**Comment by ocormont** [comment]
Bonjour Daniel et merci,

J'ai réussi à rapatrier le nombre exact de notices.
Je teste la procédure d'export - modification - import.
Une fois la procédure validée, je vous préviendrai pour supprimer la limite d'export sur le .org
