### ISSUE TITLE
Thésaurus Mise à jour 2016

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#52]
Le fichier du thésaurus mis à jour pour l'année 2016 est partagé [**ici**](https://docs.google.com/spreadsheets/d/1iVwf1jckQbjSWiAV00f6Ihj51r3dbp0PwUWFdDhCu0M/edit#gid=0)

**Comment by daniel-menard** [comment]
### Version 2.3 du thésaurus Prisme

J'ai réussi à charger la nouvelle version du thésaurus sur le site .org : 

![image](https://user-images.githubusercontent.com/3940667/27140992-4e943be4-5127-11e7-879c-f963ea4052d2.png)

Remarque : je l'ai fait uniquement sur le .org, si vous voulez que je fasse la même chose sur le .net, dites-le moi.

### Suite des opérations

Merci de vérifier que tout est ok dans la table (ça me semble bon mais mieux vaut vérifier).

Si tout est ok, il ne vous reste plus qu'à activer cette nouvelle version. Pour cela, il faut modifier la table `prisme-topics` (et peut-être aussi d'autres tables comme `prisme-topics-web` ?) en remplaçant `thesaurus:thesaurus-prisme-2.2` par `thesaurus:thesaurus-prisme-2_3` dans la colonne "source" de la ligne 2 :

![image](https://user-images.githubusercontent.com/3940667/27141641-07ac3eb4-5129-11e7-91f4-c630421dcecc.png)

Ok comme ça ?

----

### Mémo pour moi, méthode employée pour charger manuellement la nouvelle version du thésaurus : 

1. Dans le fichier Google Drive, ajout de la ligne contenant les entêtes de colonne (code, label, description, etc.)

2. Depuis Google Drive, export du fichier au format ODS LibreOffice et récupération sur mon poste local

3. Sous Libre-Office, export au format CSV sur mon poste en employant les paramètres suivants : 
  ![image](https://user-images.githubusercontent.com/3940667/27138616-3c799220-5121-11e7-9f77-b33b20393845.png)
  ![image](https://user-images.githubusercontent.com/3940667/27138651-51bd8fe2-5121-11e7-8926-d32d2c4cc9e6.png)

4. Sous Eclipse, vérif rapide des modifications effectuées en comparant la v2.2 et v2.3 : 
  ![image](https://user-images.githubusercontent.com/3940667/27138864-d399a118-5121-11e7-8e33-3790c4053377.png)

5. Sur le site .org, création d'une nouvelle table `thesaurus-prisme-2_3` par recopie de la table `thesaurus-prisme-2.2` existante : 
  ![image](https://user-images.githubusercontent.com/3940667/27139409-3f63014a-5123-11e7-89f1-21aaee517a9f.png)
  *Remarque :* le module en ligne n'accepte pas le point dans les noms de table, d'où le "**2_3**" à la place du "**2.3**"
  A ce stade, la table 2.3 a été créée, mais elle contient le contenu de la 2.2.

6. Sur le site .org, upload du fichier (en passant par la médiathèque wordpress) 

7. Sur le serveur (via une connexion ssh), recopie du fichier uploadé vers la table : 
```sh

# Le fichier v2.3 uploadé dans la médiathèque WP
$ l uploads/2017/06/thesaurus*
-rw-r--r-- 1 www-data www-data 209408 2017-06-14 17:06:37 thesaurus-prisme-2.3.txt

# La table docalist contenant une copie de la v2.2
$ l uploads/docalist-data/tables/thesaurus*
-rw-r--r-- 1 www-data www-data 213655 2017-06-14 17:04:47 uploads/docalist-data/tables/thesaurus-prisme-2_3.txt

# Remplace le contenu de la table 2_3 par le contenu du fichier uploadé
$ sudo cp uploads/2017/06/thesaurus-prisme-2.3.txt uploads/docalist-data/tables/thesaurus-prisme-2_3.txt
```

8. Sur le site, la table 2_3 contient maintenant les bonnes données : 
  ![image](https://user-images.githubusercontent.com/3940667/27140528-0cd74486-5126-11e7-810c-3f3090c9d133.png)
  Sur la copie d'écran ci-dessus, on voit par exemple le terme "conseil départemental" qui a été ajouté et qui remplace l'ancienne appellation "conseil général".


9. Suppression du fichier uploadé dans la médiathèque de WordPress

10. Commit du nouveau fichier dans le dépôt git

Terminé !

**Comment by Nicolas-L** [comment]
J'ai modifier toutes les tables Topic comme indiqué.
On dirait que ça marche, nickel.
