### ISSUE TITLE
Création d'une BDD "sanitaire"

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#53]
Un groupe de travail souhaite mettre en place une base d'articles exclusivement composée de revues du secteur sanitaire afin d'échanger des notices sur le même modèle que celui de la bdd Prisme.

- La finalité est pour l'instant essentiellement tournée vers de la mutualisation de l'indexation pour générer des fichiers d'export.
- Les notices de cette base ne devront pas être consultables par les utilisateurs non connectés (outil interne à Prisme)

**Question :** Peut-on facilement paramétrer une bdd de sorte que ses notices, une fois validées, ne soient visibles que par un ou plusieurs types d'utilisateurs connectés ?

**Comment by ocormont** [comment]
Les notices "sanitaires" ont été intégrées à la base Article
