### ISSUE TITLE
Pb sur une Notice de la base Livre

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#54]
Aucun type de notice (Livre) attribué à cette notice : http://www.documentation-sociale.org/base-livre/349/
Impossible de rentrer d'accéder au formulaire de saisie... A resaisir ?

**Comment by daniel-menard** [comment]
C'est bizarre, ça, comment ça a pu arriver ?

Inutile de re-saisir, j'ai modifié la notice directement dans la base mysql.

**Comment by Nicolas-L** [comment]
... je ne sais pas, ce sont des notices importées, je les valide tranquillement (en attente => publier).
J'ouvre la notice, je la publie et à cette étape, le type "disparaît" alors que le numéro de référence s'enregistre =>page blanche avec message d'erreur.

J'en ai d'autres là :
- http://www.documentation-sociale.org/base-livre/451/
- http://www.documentation-sociale.org/base-livre/528/


Il y en aura sans doute quelques autres

**Comment by daniel-menard** [comment]
Manifestement, il y a un bug, mais je n'arrive pas à le reproduire...

J'ai fait des essais sur la notice suivante : 

http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2390282&action=edit
(Prévention et promotion de la santé mentale : Une alliance transfrontalière innovante)

je l'ai publiée, remise en attente, republiée, etc. en utilisant des fois le formulaire complet, des fois l'édition rapide (dans la liste), mais je n'arrive pas à "perdre" le type de notice.

Pouvez-vous svp faire une liste des notices qui perdent leur type, je les modifierai toutes d'un coup en direct dans la base mysql ? Si vous pouvez noter l'ID wordpress du post (paramètre  `?post=` dans l'url du formulaire), en plus du titre, ça me ferait gagner du temps.

PS : pour la notice sur laquelle j'ai fait mes tests, elle est toujours "en attente", mais maintenant elle a un numéro de réf.

**Comment by Nicolas-L** [comment]
OK, j'en ferai la liste comme indiqué.

**Comment by Nicolas-L** [comment]
Voici la liste des notices : 

- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2390457&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2389984&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2390211&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2389328&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2390011&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2389935&action=edit
- http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2389839&action=edit&message=1

**Comment by daniel-menard** [comment]
Bonjour Nicolas,

J'ai "réparé" toutes les notices listées.

(et je n'arrive toujours pas à reproduire le bug...)


----
Mémo pour moi pour repérer les notices sans type : 

```sql
SELECT * FROM docsocorg.wp_posts 
WHERE post_type='dclreflivre' AND post_excerpt NOT LIKE '%"type":%';
```
