### ISSUE TITLE
Plantage BDD Site web

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#55]
En voulant mettre à jour la table personnalisée `prisme-topics-web-test`, à savoir changer la version de `thesaurus:prisme-domaines-2` vers `thesaurus:prisme-domaines-4-0` ça a fait plater l'affichage des notices (front et back).
Je pense que je me suis tromper : j'ai renseigné `4.0` au lieu de `4-0` avant d'enregistrer.

**Comment by Nicolas-L** [comment]
Et impossible de revenir sur l'ancienne version de la table :  Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]:

**Comment by daniel-menard** [comment]
J'ai eu un peu de mal mais c'est corrigé.

> j'ai renseigné 4.0 au lieu de 4-0 avant d'enregistrer

oui, c'était ça
