### ISSUE TITLE
Notice sans Type = Fatal Error

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#58]
Une notice s'est retrouvée sans type suite à une correction => Fatal error

[Le proxénétisme : l'invisible du marché prostitutionnel](http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2407086&action=edit) – Brouillon
 
![capture1](https://user-images.githubusercontent.com/5398758/33079393-c2bdf312-ced5-11e7-9fa1-b4501c593827.PNG)

**Comment by daniel-menard** [comment]
J'ai restauré la notice abîmée à partir de la dernière révision : 

http://www.documentation-sociale.org/wordpress/wp-admin/post.php?post=2407086&action=edit

Mais je n'ai toujours pas identifié la cause du problème (probablement la même chose que dans #54).
