### ISSUE TITLE
Styles des flux RSS

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#6]
_From @daniel-menard on August 5, 2013 10:9_

Style à re réfléchir. Pas nécessairement celui de la maquette.

(e-mail de Nicolas du 03-08-13)

_Copied from original issue: docalist/docalist#6_

**Comment by Nicolas-L** [comment]
Il ne s'agit en fait pas des flux RSS mais plutôt de la mise en valeur sur la page d'accueil des différents articles du site à la manière de flux.

Dans l'idée, chaque article de blog ou notice de bdd doit pouvoir être mis en valeur sur la page d'accueil. Une option du genre "faire apparaître en page d'accueil" permettrait au producteur de valoriser sa notice au moment de la saisie. Ex : une loi importante (Info légis) ou un rapport (BRSM), ou encore, signalement d'une notice d'ouvrage. Ces références seraient ainsi présentées comme un fil d'actu sur la colonne de droite.

Ce qui pourrait être intéressant ce serait conserver nos deux zones en colonne de droite, avec une place importante pour un article ou notice avec imagette et début de texte + lire la suite ; et une deuxième partie, plus succincte (style flux rss) qui renvoie sur des notices de produits ou articles. [à décrire le moment venu]

**Comment by ocormont** [comment]
A revoir au moment de la refonte du thème
