### ISSUE TITLE
Réduire le nombre de types de notice de la base Biblio

### ISSUE THREAD

**Issue by Nicolas-L** [reseau-prisme/site#9]
**A discuter :**

Pour l'instant, pour la base Prisme il faudrait qu'il n'y ait que les types de notices utilisés par la commission producteurs et Audiovisuel. A savoir : 
- Article de périodique
- Livre
- Film
- Mémoire ou thèse

L'idée est avant tout de simplifier le visuel et d'éviter les confusions dans cette première phase de prise en main de Docalist.

Pour le reste, il faudra interpeller la commission producteurs pour savoir si il y a d'autres besoins en perspective.

**Comment by ocormont** [comment]
Dans mon souvenir, il me semble que nous pouvons le faire simplement :
Réglages / Bases documentaires / Gestion des bases documentaires / Base Prisme / Type de notices.
Puis supprimer les types voulues.
Faire attention que ces types ne soit pas dans la base
Avant de faire les modifs, je préfère avoir l'avis de Daniel, je ne suis pas encore à 100% remis des vacances
